name: Autograding Tests
on:
  push:
  repository_dispatch:
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: cargo test
      id: cargo-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: cargo test
        setup-command: ''
        command: cargo test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CARGO-TEST_RESULTS: "${{steps.cargo-test.outputs.result}}"
      with:
        runners: cargo-test